# Generated by Django 5.2.6 on 2025-10-18 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloqId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lockerId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(max_length=50)),
                ('isOccupied', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bloq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='bloq_api.bloq')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rentId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('weight', models.FloatField()),
                ('size', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='bloq_api.locker')),
            ],
        ),
    ]
