# Generated by Django 5.2.6 on 2025-10-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloq_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='bloq_api.locker'),
        ),
    ]
