# Generated by Django 5.2.6 on 2025-10-18 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloq_api', '0002_alter_rent_locker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloq',
            name='bloqId',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='lockerId',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='closed', max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rentId',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='size',
            field=models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl')], default='medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('WAITING_DROPOFF', 'Waiting_Dropoff'), ('WAITING_PICKUP', 'Waiting_Pickup'), ('DELIVERED', 'Delivered')], default='created', max_length=20),
        ),
    ]
